### ISSUE TITLE
Login to Twitter, Google, Facebook on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by alexgonca** [strohne/Facepager#118]
Hi!
When I click on the login buttons on Ubuntu, they do not work.
(They are fine when I run Facepager on Windows.)

When I click on "Login to Google" (YouTube tab) and "Login to Facebook", I receive this message:
`Client ID missing, please adjust settings!`

When I click on "Login to Twitter" (Twitter tab), this is the message:
`'NoneType' object has no attribute 'encode'`

And when I click on "Login to Twitter" (Twitter Streaming), I get:
`Consumer key or consumer secret is missing, please adjust settings!`

On Ubuntu, I never get to the window to write down my credentials on the platform.

Any ideas?

**Comment by strohne** [comment]
Under Ubuntu (since there is no build yet) you need to register your own apps at Facebook, Google/YouTube and Twitter, see https://github.com/strohne/Facepager/blob/master/src/credentials.py.readme

You can choose to provide the app credentials in credentials.py or just click the settings button next to login. App credentials are not your user credentials (which you provide with the login button).

**Comment by strohne** [comment]
Be aware, you need to go through app review at Facebook, Twitter and YouTube. This can be quite hard, in particular for Facebook chances are low. I don't like my next sentence: if you never registered an app or never submitted one to app review, consider using the Windows version of Facepager.

**Comment by alexgonca** [comment]
I see!
Thanks a lot, Jakob!
Very good to know. :)
