### ISSUE TITLE
Copying nodes

### ISSUE THREAD

**Issue by eugenieDSP** [strohne/Facepager#135]
Another bug I have found: when I click on "Copy nodes to clipboard", Facepager copies selected fields in the "Parameters" tab but not the nodes. If I understand correctly, nodes are IDs of Facebook pages in the current example.

**Comment by strohne** [comment]
This is expected behavior. Nodes in our terminology correspond to rows in the nodes view, see https://github.com/strohne/Facepager/wiki/Layout#nodes-view

The nodes contain a) data as presented in the columns and in the data view as well as b) other nodes.

What you refer to is the Object ID (which is a property of nodes).
