### ISSUE TITLE
DLL load failed while importing shiboken2

### ISSUE THREAD

**Issue by visheshaylani** [strohne/Facepager#138]
I am having this error
ImportError: DLL load failed while importing shiboken2: The specified procedure could not be found.

Kindly let me know how to fix it.

**Comment by strohne** [comment]
I guess this is an incompatibility issue between PySide 5.11.1 and Python 3.8. Can you try using Python 3.7 when creating the virtual environmen? Maybe a later version of PySide could work as well, give it a try. At the moment, we are stuck to 5.11.1 because only this one has the needed browser modules.

**Comment by strohne** [comment]
Can you please try: `pip3 install PySide2==5.14.2` ?

**Comment by strohne** [comment]
Hi,  did you use the installer or run it from source?

There is a new release, please try it out: https://github.com/strohne/Facepager/releases

While I'm not sure whether it addresses your issue, it would be very kind of you to test against the latest version

**Comment by strohne** [comment]
Hi, could you please try whether the latest version (pre-release) works?

**Comment by strohne** [comment]
I close the issue since there are no updates.  The problem can probably be solved by installing the above mentioned package. Feel free to reopen the issue if necessary.
