### ISSUE TITLE
Do not have an access token

### ISSUE THREAD

**Issue by bnednbb** [strohne/Facepager#166]
Installed facepager 4.4 via python 3 on MacOS, and stuff do not work. First, I can't add nodes, second, I do not have an access token.

**Comment by strohne** [comment]
Hi, when installing from source (python 3) you can't use the preregistered access, this only works for the installer versions. You need to provide your own app credentials to get an acces token, see https://github.com/strohne/Facepager/wiki/FAQ#q-what-is-the-field-client-id-for

About adding nodes: can you please be more specific, what happens when you click the button for adding nodes? And did you create or open a database before?
