### ISSUE TITLE
error in page requests

### ISSUE THREAD

**Issue by antropoiese** [strohne/Facepager#174]
I'm getting an error when trying to get basic data from pages. It was working perfectly, but now I am getting this error:

"(#100) Object does not exist, cannot be loaded due to missing permission or reviewable feature, or does not support this operation. This endpoint requires the 'manage_pages' or 'pages_read_engagement' permission or the 'Page Public Content Access' feature or the 'Page Public Metadata Access' feature. Refer to https://developers.facebook.com/.../login-permissions..., https://developers.facebook.com/docs/apps/review/feature... and https://developers.facebook.com/docs/apps/review/feature... for details."

What I am doing wrong?

PS: The feed endpoint still works.

**Comment by gerickt** [comment]
same problem here

**Comment by strohne** [comment]
The permissions of the Facebook API changed, by now accessing page data is restricted. The only way would be to go through the app review with Facepager again - we decided not to to this because we don't want to risk the other permissions. You can use CrowdTangle or register an own app and go through app review. Please see the Facepager user group for more information.
