### ISSUE TITLE
Error 400 error_subcode 33

### ISSUE THREAD

**Issue by ramzymbk** [strohne/Facepager#96]
Trying to get a list of attendees to facebook events and keep getting this error.
![git](https://user-images.githubusercontent.com/44702317/47916629-12232d00-dea7-11e8-8db9-e89d041d648a.PNG)

**Comment by strohne** [comment]
I close this issue since it is not related to the development of Facepager. Please ask questions about using Facepager in the [Facebook group](https://www.facebook.com/groups/facepagerusers/). And please get familiar with the [API reference of Facebook](https://developers.facebook.com/docs/graph-api/reference), especially regarding the event endpoint. For this you need special permission. Further information can be found in the [wiki](https://github.com/strohne/Facepager/wiki/Query-Setup.-Facebook).

By the way: there is a typo in your `Resource` field.
