### ISSUE TITLE
Error 400 when trying to extract invited members from events

### ISSUE THREAD

**Issue by bretfeig** [strohne/Facepager#97]
![image](https://user-images.githubusercontent.com/11678894/47963604-77d4fd80-dffc-11e8-8521-49a67b4b91c5.png)

Any help would be great

**Comment by strohne** [comment]
I close this issue since it is not related to the development of Facepager. Please ask questions about using Facepager in the [Facebook group](https://www.facebook.com/groups/facepagerusers/). And please get familiar with the [API reference of Facebook](https://developers.facebook.com/docs/graph-api/reference), especially regarding the event endpoint. For this you need special permissions (whitelisted partners only). Further information can be found in the [wiki](https://github.com/strohne/Facepager/wiki/Query-Setup.-Facebook).
